import pandas as pd
from src.util.inspect_clusters import inspect_clusters
from src.comment_clustering.pipeline import process_and_cluster_comments
import pickle
from src.util.get_number_of_clusters import get_number_of_clusters
from src.util.append_new_data_to_csv import append_new_data_to_csv
def main():
    # Load the labeled comments CSV generated by your pipeline
    df = pd.read_csv(r'output\labeled_comments.csv')

    # Inspect clusters — print distinct comments in each cluster
    inspect_clusters(df)


if __name__ == '__main__':


    append_new_data_to_csv()

    # Run the full pipeline (this saves cluster labels to a file)
    process_and_cluster_comments(
        input_csv=r'data\data.csv',
        output_csv=r'output\labeled_comments.csv',
        embeddings_file=r'output\saved_embeddings.pkl',
        cluster_labels_file=r'output\saved_cluster_labels.pkl',
        mapping_file=r'output\cluster_label_mapping.json',
        hierarchy_file=r'output\comment_hierarchy.json'
    )
    
    # Load the saved cluster labels
    with open(r'output\saved_cluster_labels.pkl', 'rb') as f:
        cluster_labels = pickle.load(f)
    main()
    # Check the number of clusters
    num_clusters = get_number_of_clusters(cluster_labels)
    print(f"Number of clusters formed: {num_clusters}")
